# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

# All tasks on Windows
- job: test_all_windows
  displayName: Test all tests (Windows)
  condition: and(succeeded(), not(variables.task), eq(variables.os, 'Windows_NT'))
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: .travis.yml

# All tasks on Linux
- job: test_all_linux
  displayName: Test all tests (Linux)
  condition: and(succeeded(), not(variables.task), eq(variables.os, 'Linux'))
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: .travis.yml